
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace VikkiSoft_BLL.DAL
{
	public abstract class _Advice : SqlClientEntity
	{
		public _Advice()
		{
			this.QuerySource = "Advice";
			this.MappingName = "Advice";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "LoadAllAdvice]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int AdviceID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.AdviceID, AdviceID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "LoadAdviceByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter AdviceID
			{
				get
				{
					return new SqlParameter("@AdviceID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Question
			{
				get
				{
					return new SqlParameter("@Question", SqlDbType.VarChar, 250);
				}
			}
			
			public static SqlParameter Answer
			{
				get
				{
					return new SqlParameter("@Answer", SqlDbType.VarChar, 2147483647);
				}
			}
			
			public static SqlParameter Question_ru
			{
				get
				{
					return new SqlParameter("@Question_ru", SqlDbType.VarChar, 250);
				}
			}
			
			public static SqlParameter Question_en
			{
				get
				{
					return new SqlParameter("@Question_en", SqlDbType.VarChar, 250);
				}
			}
			
			public static SqlParameter Answer_ru
			{
				get
				{
					return new SqlParameter("@Answer_ru", SqlDbType.VarChar, 2147483647);
				}
			}
			
			public static SqlParameter Answer_en
			{
				get
				{
					return new SqlParameter("@Answer_en", SqlDbType.VarChar, 2147483647);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string AdviceID = "AdviceID";
            public const string Question = "Question";
            public const string Answer = "Answer";
            public const string Question_ru = "Question_ru";
            public const string Question_en = "Question_en";
            public const string Answer_ru = "Answer_ru";
            public const string Answer_en = "Answer_en";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[AdviceID] = _Advice.PropertyNames.AdviceID;
					ht[Question] = _Advice.PropertyNames.Question;
					ht[Answer] = _Advice.PropertyNames.Answer;
					ht[Question_ru] = _Advice.PropertyNames.Question_ru;
					ht[Question_en] = _Advice.PropertyNames.Question_en;
					ht[Answer_ru] = _Advice.PropertyNames.Answer_ru;
					ht[Answer_en] = _Advice.PropertyNames.Answer_en;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string AdviceID = "AdviceID";
            public const string Question = "Question";
            public const string Answer = "Answer";
            public const string Question_ru = "Question_ru";
            public const string Question_en = "Question_en";
            public const string Answer_ru = "Answer_ru";
            public const string Answer_en = "Answer_en";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[AdviceID] = _Advice.ColumnNames.AdviceID;
					ht[Question] = _Advice.ColumnNames.Question;
					ht[Answer] = _Advice.ColumnNames.Answer;
					ht[Question_ru] = _Advice.ColumnNames.Question_ru;
					ht[Question_en] = _Advice.ColumnNames.Question_en;
					ht[Answer_ru] = _Advice.ColumnNames.Answer_ru;
					ht[Answer_en] = _Advice.ColumnNames.Answer_en;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string AdviceID = "s_AdviceID";
            public const string Question = "s_Question";
            public const string Answer = "s_Answer";
            public const string Question_ru = "s_Question_ru";
            public const string Question_en = "s_Question_en";
            public const string Answer_ru = "s_Answer_ru";
            public const string Answer_en = "s_Answer_en";

		}
		#endregion		
		
		#region Properties
	
		public virtual int AdviceID
	    {
			get
	        {
				return base.Getint(ColumnNames.AdviceID);
			}
			set
	        {
				base.Setint(ColumnNames.AdviceID, value);
			}
		}

		public virtual string Question
	    {
			get
	        {
				return base.Getstring(ColumnNames.Question);
			}
			set
	        {
				base.Setstring(ColumnNames.Question, value);
			}
		}

		public virtual string Answer
	    {
			get
	        {
				return base.Getstring(ColumnNames.Answer);
			}
			set
	        {
				base.Setstring(ColumnNames.Answer, value);
			}
		}

		public virtual string Question_ru
	    {
			get
	        {
				return base.Getstring(ColumnNames.Question_ru);
			}
			set
	        {
				base.Setstring(ColumnNames.Question_ru, value);
			}
		}

		public virtual string Question_en
	    {
			get
	        {
				return base.Getstring(ColumnNames.Question_en);
			}
			set
	        {
				base.Setstring(ColumnNames.Question_en, value);
			}
		}

		public virtual string Answer_ru
	    {
			get
	        {
				return base.Getstring(ColumnNames.Answer_ru);
			}
			set
	        {
				base.Setstring(ColumnNames.Answer_ru, value);
			}
		}

		public virtual string Answer_en
	    {
			get
	        {
				return base.Getstring(ColumnNames.Answer_en);
			}
			set
	        {
				base.Setstring(ColumnNames.Answer_en, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_AdviceID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AdviceID) ? string.Empty : base.GetintAsString(ColumnNames.AdviceID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AdviceID);
				else
					this.AdviceID = base.SetintAsString(ColumnNames.AdviceID, value);
			}
		}

		public virtual string s_Question
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Question) ? string.Empty : base.GetstringAsString(ColumnNames.Question);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Question);
				else
					this.Question = base.SetstringAsString(ColumnNames.Question, value);
			}
		}

		public virtual string s_Answer
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Answer) ? string.Empty : base.GetstringAsString(ColumnNames.Answer);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Answer);
				else
					this.Answer = base.SetstringAsString(ColumnNames.Answer, value);
			}
		}

		public virtual string s_Question_ru
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Question_ru) ? string.Empty : base.GetstringAsString(ColumnNames.Question_ru);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Question_ru);
				else
					this.Question_ru = base.SetstringAsString(ColumnNames.Question_ru, value);
			}
		}

		public virtual string s_Question_en
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Question_en) ? string.Empty : base.GetstringAsString(ColumnNames.Question_en);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Question_en);
				else
					this.Question_en = base.SetstringAsString(ColumnNames.Question_en, value);
			}
		}

		public virtual string s_Answer_ru
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Answer_ru) ? string.Empty : base.GetstringAsString(ColumnNames.Answer_ru);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Answer_ru);
				else
					this.Answer_ru = base.SetstringAsString(ColumnNames.Answer_ru, value);
			}
		}

		public virtual string s_Answer_en
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Answer_en) ? string.Empty : base.GetstringAsString(ColumnNames.Answer_en);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Answer_en);
				else
					this.Answer_en = base.SetstringAsString(ColumnNames.Answer_en, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter AdviceID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AdviceID, Parameters.AdviceID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Question
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Question, Parameters.Question);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Answer
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Answer, Parameters.Answer);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Question_ru
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Question_ru, Parameters.Question_ru);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Question_en
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Question_en, Parameters.Question_en);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Answer_ru
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Answer_ru, Parameters.Answer_ru);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Answer_en
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Answer_en, Parameters.Answer_en);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter AdviceID
		    {
				get
		        {
					if(_AdviceID_W == null)
	        	    {
						_AdviceID_W = TearOff.AdviceID;
					}
					return _AdviceID_W;
				}
			}

			public WhereParameter Question
		    {
				get
		        {
					if(_Question_W == null)
	        	    {
						_Question_W = TearOff.Question;
					}
					return _Question_W;
				}
			}

			public WhereParameter Answer
		    {
				get
		        {
					if(_Answer_W == null)
	        	    {
						_Answer_W = TearOff.Answer;
					}
					return _Answer_W;
				}
			}

			public WhereParameter Question_ru
		    {
				get
		        {
					if(_Question_ru_W == null)
	        	    {
						_Question_ru_W = TearOff.Question_ru;
					}
					return _Question_ru_W;
				}
			}

			public WhereParameter Question_en
		    {
				get
		        {
					if(_Question_en_W == null)
	        	    {
						_Question_en_W = TearOff.Question_en;
					}
					return _Question_en_W;
				}
			}

			public WhereParameter Answer_ru
		    {
				get
		        {
					if(_Answer_ru_W == null)
	        	    {
						_Answer_ru_W = TearOff.Answer_ru;
					}
					return _Answer_ru_W;
				}
			}

			public WhereParameter Answer_en
		    {
				get
		        {
					if(_Answer_en_W == null)
	        	    {
						_Answer_en_W = TearOff.Answer_en;
					}
					return _Answer_en_W;
				}
			}

			private WhereParameter _AdviceID_W = null;
			private WhereParameter _Question_W = null;
			private WhereParameter _Answer_W = null;
			private WhereParameter _Question_ru_W = null;
			private WhereParameter _Question_en_W = null;
			private WhereParameter _Answer_ru_W = null;
			private WhereParameter _Answer_en_W = null;

			public void WhereClauseReset()
			{
				_AdviceID_W = null;
				_Question_W = null;
				_Answer_W = null;
				_Question_ru_W = null;
				_Question_en_W = null;
				_Answer_ru_W = null;
				_Answer_en_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter AdviceID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AdviceID, Parameters.AdviceID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Question
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Question, Parameters.Question);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Answer
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Answer, Parameters.Answer);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Question_ru
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Question_ru, Parameters.Question_ru);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Question_en
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Question_en, Parameters.Question_en);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Answer_ru
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Answer_ru, Parameters.Answer_ru);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Answer_en
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Answer_en, Parameters.Answer_en);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter AdviceID
		    {
				get
		        {
					if(_AdviceID_W == null)
	        	    {
						_AdviceID_W = TearOff.AdviceID;
					}
					return _AdviceID_W;
				}
			}

			public AggregateParameter Question
		    {
				get
		        {
					if(_Question_W == null)
	        	    {
						_Question_W = TearOff.Question;
					}
					return _Question_W;
				}
			}

			public AggregateParameter Answer
		    {
				get
		        {
					if(_Answer_W == null)
	        	    {
						_Answer_W = TearOff.Answer;
					}
					return _Answer_W;
				}
			}

			public AggregateParameter Question_ru
		    {
				get
		        {
					if(_Question_ru_W == null)
	        	    {
						_Question_ru_W = TearOff.Question_ru;
					}
					return _Question_ru_W;
				}
			}

			public AggregateParameter Question_en
		    {
				get
		        {
					if(_Question_en_W == null)
	        	    {
						_Question_en_W = TearOff.Question_en;
					}
					return _Question_en_W;
				}
			}

			public AggregateParameter Answer_ru
		    {
				get
		        {
					if(_Answer_ru_W == null)
	        	    {
						_Answer_ru_W = TearOff.Answer_ru;
					}
					return _Answer_ru_W;
				}
			}

			public AggregateParameter Answer_en
		    {
				get
		        {
					if(_Answer_en_W == null)
	        	    {
						_Answer_en_W = TearOff.Answer_en;
					}
					return _Answer_en_W;
				}
			}

			private AggregateParameter _AdviceID_W = null;
			private AggregateParameter _Question_W = null;
			private AggregateParameter _Answer_W = null;
			private AggregateParameter _Question_ru_W = null;
			private AggregateParameter _Question_en_W = null;
			private AggregateParameter _Answer_ru_W = null;
			private AggregateParameter _Answer_en_W = null;

			public void AggregateClauseReset()
			{
				_AdviceID_W = null;
				_Question_W = null;
				_Answer_W = null;
				_Question_ru_W = null;
				_Question_en_W = null;
				_Answer_ru_W = null;
				_Answer_en_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "InsertAdvice]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.AdviceID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "UpdateAdvice]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "DeleteAdvice]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.AdviceID);
			p.SourceColumn = ColumnNames.AdviceID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.AdviceID);
			p.SourceColumn = ColumnNames.AdviceID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Question);
			p.SourceColumn = ColumnNames.Question;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Answer);
			p.SourceColumn = ColumnNames.Answer;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Question_ru);
			p.SourceColumn = ColumnNames.Question_ru;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Question_en);
			p.SourceColumn = ColumnNames.Question_en;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Answer_ru);
			p.SourceColumn = ColumnNames.Answer_ru;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Answer_en);
			p.SourceColumn = ColumnNames.Answer_en;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
