
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace VikkiSoft_BLL.DAL
{
	public abstract class _Category : SqlClientEntity
	{
		public _Category()
		{
			this.QuerySource = "Category";
			this.MappingName = "Category";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "LoadAllCategory]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int CategoryID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.CategoryID, CategoryID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "LoadCategoryByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter CategoryID
			{
				get
				{
					return new SqlParameter("@CategoryID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Name
			{
				get
				{
					return new SqlParameter("@Name", SqlDbType.VarChar, 255);
				}
			}
			
			public static SqlParameter IsGallery
			{
				get
				{
					return new SqlParameter("@IsGallery", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter PriceFrom
			{
				get
				{
					return new SqlParameter("@PriceFrom", SqlDbType.Money, 0);
				}
			}
			
			public static SqlParameter PriceTo
			{
				get
				{
					return new SqlParameter("@PriceTo", SqlDbType.Money, 0);
				}
			}
			
			public static SqlParameter DisplayOnPrice
			{
				get
				{
					return new SqlParameter("@DisplayOnPrice", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter Title
			{
				get
				{
					return new SqlParameter("@Title", SqlDbType.VarChar, 255);
				}
			}
			
			public static SqlParameter CategoryContent
			{
				get
				{
					return new SqlParameter("@CategoryContent", SqlDbType.VarChar, 2147483647);
				}
			}
			
			public static SqlParameter Name_ru
			{
				get
				{
					return new SqlParameter("@Name_ru", SqlDbType.VarChar, 255);
				}
			}
			
			public static SqlParameter Title_ru
			{
				get
				{
					return new SqlParameter("@Title_ru", SqlDbType.VarChar, 255);
				}
			}
			
			public static SqlParameter CategoryContent_ru
			{
				get
				{
					return new SqlParameter("@CategoryContent_ru", SqlDbType.VarChar, 2147483647);
				}
			}
			
			public static SqlParameter Name_en
			{
				get
				{
					return new SqlParameter("@Name_en", SqlDbType.VarChar, 255);
				}
			}
			
			public static SqlParameter Title_en
			{
				get
				{
					return new SqlParameter("@Title_en", SqlDbType.VarChar, 255);
				}
			}
			
			public static SqlParameter CategoryContent_en
			{
				get
				{
					return new SqlParameter("@CategoryContent_en", SqlDbType.VarChar, 2147483647);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string CategoryID = "CategoryID";
            public const string Name = "Name";
            public const string IsGallery = "IsGallery";
            public const string PriceFrom = "PriceFrom";
            public const string PriceTo = "PriceTo";
            public const string DisplayOnPrice = "DisplayOnPrice";
            public const string Title = "Title";
            public const string CategoryContent = "CategoryContent";
            public const string Name_ru = "Name_ru";
            public const string Title_ru = "Title_ru";
            public const string CategoryContent_ru = "CategoryContent_ru";
            public const string Name_en = "Name_en";
            public const string Title_en = "Title_en";
            public const string CategoryContent_en = "CategoryContent_en";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[CategoryID] = _Category.PropertyNames.CategoryID;
					ht[Name] = _Category.PropertyNames.Name;
					ht[IsGallery] = _Category.PropertyNames.IsGallery;
					ht[PriceFrom] = _Category.PropertyNames.PriceFrom;
					ht[PriceTo] = _Category.PropertyNames.PriceTo;
					ht[DisplayOnPrice] = _Category.PropertyNames.DisplayOnPrice;
					ht[Title] = _Category.PropertyNames.Title;
					ht[CategoryContent] = _Category.PropertyNames.CategoryContent;
					ht[Name_ru] = _Category.PropertyNames.Name_ru;
					ht[Title_ru] = _Category.PropertyNames.Title_ru;
					ht[CategoryContent_ru] = _Category.PropertyNames.CategoryContent_ru;
					ht[Name_en] = _Category.PropertyNames.Name_en;
					ht[Title_en] = _Category.PropertyNames.Title_en;
					ht[CategoryContent_en] = _Category.PropertyNames.CategoryContent_en;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string CategoryID = "CategoryID";
            public const string Name = "Name";
            public const string IsGallery = "IsGallery";
            public const string PriceFrom = "PriceFrom";
            public const string PriceTo = "PriceTo";
            public const string DisplayOnPrice = "DisplayOnPrice";
            public const string Title = "Title";
            public const string CategoryContent = "CategoryContent";
            public const string Name_ru = "Name_ru";
            public const string Title_ru = "Title_ru";
            public const string CategoryContent_ru = "CategoryContent_ru";
            public const string Name_en = "Name_en";
            public const string Title_en = "Title_en";
            public const string CategoryContent_en = "CategoryContent_en";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[CategoryID] = _Category.ColumnNames.CategoryID;
					ht[Name] = _Category.ColumnNames.Name;
					ht[IsGallery] = _Category.ColumnNames.IsGallery;
					ht[PriceFrom] = _Category.ColumnNames.PriceFrom;
					ht[PriceTo] = _Category.ColumnNames.PriceTo;
					ht[DisplayOnPrice] = _Category.ColumnNames.DisplayOnPrice;
					ht[Title] = _Category.ColumnNames.Title;
					ht[CategoryContent] = _Category.ColumnNames.CategoryContent;
					ht[Name_ru] = _Category.ColumnNames.Name_ru;
					ht[Title_ru] = _Category.ColumnNames.Title_ru;
					ht[CategoryContent_ru] = _Category.ColumnNames.CategoryContent_ru;
					ht[Name_en] = _Category.ColumnNames.Name_en;
					ht[Title_en] = _Category.ColumnNames.Title_en;
					ht[CategoryContent_en] = _Category.ColumnNames.CategoryContent_en;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string CategoryID = "s_CategoryID";
            public const string Name = "s_Name";
            public const string IsGallery = "s_IsGallery";
            public const string PriceFrom = "s_PriceFrom";
            public const string PriceTo = "s_PriceTo";
            public const string DisplayOnPrice = "s_DisplayOnPrice";
            public const string Title = "s_Title";
            public const string CategoryContent = "s_CategoryContent";
            public const string Name_ru = "s_Name_ru";
            public const string Title_ru = "s_Title_ru";
            public const string CategoryContent_ru = "s_CategoryContent_ru";
            public const string Name_en = "s_Name_en";
            public const string Title_en = "s_Title_en";
            public const string CategoryContent_en = "s_CategoryContent_en";

		}
		#endregion		
		
		#region Properties
	
		public virtual int CategoryID
	    {
			get
	        {
				return base.Getint(ColumnNames.CategoryID);
			}
			set
	        {
				base.Setint(ColumnNames.CategoryID, value);
			}
		}

		public virtual string Name
	    {
			get
	        {
				return base.Getstring(ColumnNames.Name);
			}
			set
	        {
				base.Setstring(ColumnNames.Name, value);
			}
		}

		public virtual bool IsGallery
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsGallery);
			}
			set
	        {
				base.Setbool(ColumnNames.IsGallery, value);
			}
		}

		public virtual decimal PriceFrom
	    {
			get
	        {
				return base.Getdecimal(ColumnNames.PriceFrom);
			}
			set
	        {
				base.Setdecimal(ColumnNames.PriceFrom, value);
			}
		}

		public virtual decimal PriceTo
	    {
			get
	        {
				return base.Getdecimal(ColumnNames.PriceTo);
			}
			set
	        {
				base.Setdecimal(ColumnNames.PriceTo, value);
			}
		}

		public virtual bool DisplayOnPrice
	    {
			get
	        {
				return base.Getbool(ColumnNames.DisplayOnPrice);
			}
			set
	        {
				base.Setbool(ColumnNames.DisplayOnPrice, value);
			}
		}

		public virtual string Title
	    {
			get
	        {
				return base.Getstring(ColumnNames.Title);
			}
			set
	        {
				base.Setstring(ColumnNames.Title, value);
			}
		}

		public virtual string CategoryContent
	    {
			get
	        {
				return base.Getstring(ColumnNames.CategoryContent);
			}
			set
	        {
				base.Setstring(ColumnNames.CategoryContent, value);
			}
		}

		public virtual string Name_ru
	    {
			get
	        {
				return base.Getstring(ColumnNames.Name_ru);
			}
			set
	        {
				base.Setstring(ColumnNames.Name_ru, value);
			}
		}

		public virtual string Title_ru
	    {
			get
	        {
				return base.Getstring(ColumnNames.Title_ru);
			}
			set
	        {
				base.Setstring(ColumnNames.Title_ru, value);
			}
		}

		public virtual string CategoryContent_ru
	    {
			get
	        {
				return base.Getstring(ColumnNames.CategoryContent_ru);
			}
			set
	        {
				base.Setstring(ColumnNames.CategoryContent_ru, value);
			}
		}

		public virtual string Name_en
	    {
			get
	        {
				return base.Getstring(ColumnNames.Name_en);
			}
			set
	        {
				base.Setstring(ColumnNames.Name_en, value);
			}
		}

		public virtual string Title_en
	    {
			get
	        {
				return base.Getstring(ColumnNames.Title_en);
			}
			set
	        {
				base.Setstring(ColumnNames.Title_en, value);
			}
		}

		public virtual string CategoryContent_en
	    {
			get
	        {
				return base.Getstring(ColumnNames.CategoryContent_en);
			}
			set
	        {
				base.Setstring(ColumnNames.CategoryContent_en, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_CategoryID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CategoryID) ? string.Empty : base.GetintAsString(ColumnNames.CategoryID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CategoryID);
				else
					this.CategoryID = base.SetintAsString(ColumnNames.CategoryID, value);
			}
		}

		public virtual string s_Name
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Name) ? string.Empty : base.GetstringAsString(ColumnNames.Name);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Name);
				else
					this.Name = base.SetstringAsString(ColumnNames.Name, value);
			}
		}

		public virtual string s_IsGallery
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsGallery) ? string.Empty : base.GetboolAsString(ColumnNames.IsGallery);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsGallery);
				else
					this.IsGallery = base.SetboolAsString(ColumnNames.IsGallery, value);
			}
		}

		public virtual string s_PriceFrom
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.PriceFrom) ? string.Empty : base.GetdecimalAsString(ColumnNames.PriceFrom);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.PriceFrom);
				else
					this.PriceFrom = base.SetdecimalAsString(ColumnNames.PriceFrom, value);
			}
		}

		public virtual string s_PriceTo
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.PriceTo) ? string.Empty : base.GetdecimalAsString(ColumnNames.PriceTo);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.PriceTo);
				else
					this.PriceTo = base.SetdecimalAsString(ColumnNames.PriceTo, value);
			}
		}

		public virtual string s_DisplayOnPrice
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.DisplayOnPrice) ? string.Empty : base.GetboolAsString(ColumnNames.DisplayOnPrice);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.DisplayOnPrice);
				else
					this.DisplayOnPrice = base.SetboolAsString(ColumnNames.DisplayOnPrice, value);
			}
		}

		public virtual string s_Title
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Title) ? string.Empty : base.GetstringAsString(ColumnNames.Title);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Title);
				else
					this.Title = base.SetstringAsString(ColumnNames.Title, value);
			}
		}

		public virtual string s_CategoryContent
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CategoryContent) ? string.Empty : base.GetstringAsString(ColumnNames.CategoryContent);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CategoryContent);
				else
					this.CategoryContent = base.SetstringAsString(ColumnNames.CategoryContent, value);
			}
		}

		public virtual string s_Name_ru
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Name_ru) ? string.Empty : base.GetstringAsString(ColumnNames.Name_ru);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Name_ru);
				else
					this.Name_ru = base.SetstringAsString(ColumnNames.Name_ru, value);
			}
		}

		public virtual string s_Title_ru
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Title_ru) ? string.Empty : base.GetstringAsString(ColumnNames.Title_ru);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Title_ru);
				else
					this.Title_ru = base.SetstringAsString(ColumnNames.Title_ru, value);
			}
		}

		public virtual string s_CategoryContent_ru
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CategoryContent_ru) ? string.Empty : base.GetstringAsString(ColumnNames.CategoryContent_ru);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CategoryContent_ru);
				else
					this.CategoryContent_ru = base.SetstringAsString(ColumnNames.CategoryContent_ru, value);
			}
		}

		public virtual string s_Name_en
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Name_en) ? string.Empty : base.GetstringAsString(ColumnNames.Name_en);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Name_en);
				else
					this.Name_en = base.SetstringAsString(ColumnNames.Name_en, value);
			}
		}

		public virtual string s_Title_en
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Title_en) ? string.Empty : base.GetstringAsString(ColumnNames.Title_en);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Title_en);
				else
					this.Title_en = base.SetstringAsString(ColumnNames.Title_en, value);
			}
		}

		public virtual string s_CategoryContent_en
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CategoryContent_en) ? string.Empty : base.GetstringAsString(ColumnNames.CategoryContent_en);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CategoryContent_en);
				else
					this.CategoryContent_en = base.SetstringAsString(ColumnNames.CategoryContent_en, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter CategoryID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CategoryID, Parameters.CategoryID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Name
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsGallery
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsGallery, Parameters.IsGallery);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter PriceFrom
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.PriceFrom, Parameters.PriceFrom);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter PriceTo
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.PriceTo, Parameters.PriceTo);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter DisplayOnPrice
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.DisplayOnPrice, Parameters.DisplayOnPrice);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Title
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Title, Parameters.Title);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CategoryContent
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CategoryContent, Parameters.CategoryContent);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Name_ru
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Name_ru, Parameters.Name_ru);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Title_ru
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Title_ru, Parameters.Title_ru);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CategoryContent_ru
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CategoryContent_ru, Parameters.CategoryContent_ru);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Name_en
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Name_en, Parameters.Name_en);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Title_en
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Title_en, Parameters.Title_en);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CategoryContent_en
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CategoryContent_en, Parameters.CategoryContent_en);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter CategoryID
		    {
				get
		        {
					if(_CategoryID_W == null)
	        	    {
						_CategoryID_W = TearOff.CategoryID;
					}
					return _CategoryID_W;
				}
			}

			public WhereParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public WhereParameter IsGallery
		    {
				get
		        {
					if(_IsGallery_W == null)
	        	    {
						_IsGallery_W = TearOff.IsGallery;
					}
					return _IsGallery_W;
				}
			}

			public WhereParameter PriceFrom
		    {
				get
		        {
					if(_PriceFrom_W == null)
	        	    {
						_PriceFrom_W = TearOff.PriceFrom;
					}
					return _PriceFrom_W;
				}
			}

			public WhereParameter PriceTo
		    {
				get
		        {
					if(_PriceTo_W == null)
	        	    {
						_PriceTo_W = TearOff.PriceTo;
					}
					return _PriceTo_W;
				}
			}

			public WhereParameter DisplayOnPrice
		    {
				get
		        {
					if(_DisplayOnPrice_W == null)
	        	    {
						_DisplayOnPrice_W = TearOff.DisplayOnPrice;
					}
					return _DisplayOnPrice_W;
				}
			}

			public WhereParameter Title
		    {
				get
		        {
					if(_Title_W == null)
	        	    {
						_Title_W = TearOff.Title;
					}
					return _Title_W;
				}
			}

			public WhereParameter CategoryContent
		    {
				get
		        {
					if(_CategoryContent_W == null)
	        	    {
						_CategoryContent_W = TearOff.CategoryContent;
					}
					return _CategoryContent_W;
				}
			}

			public WhereParameter Name_ru
		    {
				get
		        {
					if(_Name_ru_W == null)
	        	    {
						_Name_ru_W = TearOff.Name_ru;
					}
					return _Name_ru_W;
				}
			}

			public WhereParameter Title_ru
		    {
				get
		        {
					if(_Title_ru_W == null)
	        	    {
						_Title_ru_W = TearOff.Title_ru;
					}
					return _Title_ru_W;
				}
			}

			public WhereParameter CategoryContent_ru
		    {
				get
		        {
					if(_CategoryContent_ru_W == null)
	        	    {
						_CategoryContent_ru_W = TearOff.CategoryContent_ru;
					}
					return _CategoryContent_ru_W;
				}
			}

			public WhereParameter Name_en
		    {
				get
		        {
					if(_Name_en_W == null)
	        	    {
						_Name_en_W = TearOff.Name_en;
					}
					return _Name_en_W;
				}
			}

			public WhereParameter Title_en
		    {
				get
		        {
					if(_Title_en_W == null)
	        	    {
						_Title_en_W = TearOff.Title_en;
					}
					return _Title_en_W;
				}
			}

			public WhereParameter CategoryContent_en
		    {
				get
		        {
					if(_CategoryContent_en_W == null)
	        	    {
						_CategoryContent_en_W = TearOff.CategoryContent_en;
					}
					return _CategoryContent_en_W;
				}
			}

			private WhereParameter _CategoryID_W = null;
			private WhereParameter _Name_W = null;
			private WhereParameter _IsGallery_W = null;
			private WhereParameter _PriceFrom_W = null;
			private WhereParameter _PriceTo_W = null;
			private WhereParameter _DisplayOnPrice_W = null;
			private WhereParameter _Title_W = null;
			private WhereParameter _CategoryContent_W = null;
			private WhereParameter _Name_ru_W = null;
			private WhereParameter _Title_ru_W = null;
			private WhereParameter _CategoryContent_ru_W = null;
			private WhereParameter _Name_en_W = null;
			private WhereParameter _Title_en_W = null;
			private WhereParameter _CategoryContent_en_W = null;

			public void WhereClauseReset()
			{
				_CategoryID_W = null;
				_Name_W = null;
				_IsGallery_W = null;
				_PriceFrom_W = null;
				_PriceTo_W = null;
				_DisplayOnPrice_W = null;
				_Title_W = null;
				_CategoryContent_W = null;
				_Name_ru_W = null;
				_Title_ru_W = null;
				_CategoryContent_ru_W = null;
				_Name_en_W = null;
				_Title_en_W = null;
				_CategoryContent_en_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter CategoryID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CategoryID, Parameters.CategoryID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Name
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsGallery
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsGallery, Parameters.IsGallery);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter PriceFrom
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.PriceFrom, Parameters.PriceFrom);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter PriceTo
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.PriceTo, Parameters.PriceTo);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter DisplayOnPrice
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.DisplayOnPrice, Parameters.DisplayOnPrice);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Title
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Title, Parameters.Title);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CategoryContent
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CategoryContent, Parameters.CategoryContent);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Name_ru
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Name_ru, Parameters.Name_ru);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Title_ru
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Title_ru, Parameters.Title_ru);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CategoryContent_ru
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CategoryContent_ru, Parameters.CategoryContent_ru);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Name_en
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Name_en, Parameters.Name_en);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Title_en
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Title_en, Parameters.Title_en);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CategoryContent_en
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CategoryContent_en, Parameters.CategoryContent_en);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter CategoryID
		    {
				get
		        {
					if(_CategoryID_W == null)
	        	    {
						_CategoryID_W = TearOff.CategoryID;
					}
					return _CategoryID_W;
				}
			}

			public AggregateParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public AggregateParameter IsGallery
		    {
				get
		        {
					if(_IsGallery_W == null)
	        	    {
						_IsGallery_W = TearOff.IsGallery;
					}
					return _IsGallery_W;
				}
			}

			public AggregateParameter PriceFrom
		    {
				get
		        {
					if(_PriceFrom_W == null)
	        	    {
						_PriceFrom_W = TearOff.PriceFrom;
					}
					return _PriceFrom_W;
				}
			}

			public AggregateParameter PriceTo
		    {
				get
		        {
					if(_PriceTo_W == null)
	        	    {
						_PriceTo_W = TearOff.PriceTo;
					}
					return _PriceTo_W;
				}
			}

			public AggregateParameter DisplayOnPrice
		    {
				get
		        {
					if(_DisplayOnPrice_W == null)
	        	    {
						_DisplayOnPrice_W = TearOff.DisplayOnPrice;
					}
					return _DisplayOnPrice_W;
				}
			}

			public AggregateParameter Title
		    {
				get
		        {
					if(_Title_W == null)
	        	    {
						_Title_W = TearOff.Title;
					}
					return _Title_W;
				}
			}

			public AggregateParameter CategoryContent
		    {
				get
		        {
					if(_CategoryContent_W == null)
	        	    {
						_CategoryContent_W = TearOff.CategoryContent;
					}
					return _CategoryContent_W;
				}
			}

			public AggregateParameter Name_ru
		    {
				get
		        {
					if(_Name_ru_W == null)
	        	    {
						_Name_ru_W = TearOff.Name_ru;
					}
					return _Name_ru_W;
				}
			}

			public AggregateParameter Title_ru
		    {
				get
		        {
					if(_Title_ru_W == null)
	        	    {
						_Title_ru_W = TearOff.Title_ru;
					}
					return _Title_ru_W;
				}
			}

			public AggregateParameter CategoryContent_ru
		    {
				get
		        {
					if(_CategoryContent_ru_W == null)
	        	    {
						_CategoryContent_ru_W = TearOff.CategoryContent_ru;
					}
					return _CategoryContent_ru_W;
				}
			}

			public AggregateParameter Name_en
		    {
				get
		        {
					if(_Name_en_W == null)
	        	    {
						_Name_en_W = TearOff.Name_en;
					}
					return _Name_en_W;
				}
			}

			public AggregateParameter Title_en
		    {
				get
		        {
					if(_Title_en_W == null)
	        	    {
						_Title_en_W = TearOff.Title_en;
					}
					return _Title_en_W;
				}
			}

			public AggregateParameter CategoryContent_en
		    {
				get
		        {
					if(_CategoryContent_en_W == null)
	        	    {
						_CategoryContent_en_W = TearOff.CategoryContent_en;
					}
					return _CategoryContent_en_W;
				}
			}

			private AggregateParameter _CategoryID_W = null;
			private AggregateParameter _Name_W = null;
			private AggregateParameter _IsGallery_W = null;
			private AggregateParameter _PriceFrom_W = null;
			private AggregateParameter _PriceTo_W = null;
			private AggregateParameter _DisplayOnPrice_W = null;
			private AggregateParameter _Title_W = null;
			private AggregateParameter _CategoryContent_W = null;
			private AggregateParameter _Name_ru_W = null;
			private AggregateParameter _Title_ru_W = null;
			private AggregateParameter _CategoryContent_ru_W = null;
			private AggregateParameter _Name_en_W = null;
			private AggregateParameter _Title_en_W = null;
			private AggregateParameter _CategoryContent_en_W = null;

			public void AggregateClauseReset()
			{
				_CategoryID_W = null;
				_Name_W = null;
				_IsGallery_W = null;
				_PriceFrom_W = null;
				_PriceTo_W = null;
				_DisplayOnPrice_W = null;
				_Title_W = null;
				_CategoryContent_W = null;
				_Name_ru_W = null;
				_Title_ru_W = null;
				_CategoryContent_ru_W = null;
				_Name_en_W = null;
				_Title_en_W = null;
				_CategoryContent_en_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "InsertCategory]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.CategoryID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "UpdateCategory]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "DeleteCategory]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.CategoryID);
			p.SourceColumn = ColumnNames.CategoryID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.CategoryID);
			p.SourceColumn = ColumnNames.CategoryID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Name);
			p.SourceColumn = ColumnNames.Name;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsGallery);
			p.SourceColumn = ColumnNames.IsGallery;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.PriceFrom);
			p.SourceColumn = ColumnNames.PriceFrom;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.PriceTo);
			p.SourceColumn = ColumnNames.PriceTo;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.DisplayOnPrice);
			p.SourceColumn = ColumnNames.DisplayOnPrice;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Title);
			p.SourceColumn = ColumnNames.Title;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CategoryContent);
			p.SourceColumn = ColumnNames.CategoryContent;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Name_ru);
			p.SourceColumn = ColumnNames.Name_ru;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Title_ru);
			p.SourceColumn = ColumnNames.Title_ru;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CategoryContent_ru);
			p.SourceColumn = ColumnNames.CategoryContent_ru;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Name_en);
			p.SourceColumn = ColumnNames.Name_en;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Title_en);
			p.SourceColumn = ColumnNames.Title_en;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CategoryContent_en);
			p.SourceColumn = ColumnNames.CategoryContent_en;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
