
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace VikkiSoft_BLL.DAL
{
	public abstract class _Gallery : SqlClientEntity
	{
		public _Gallery()
		{
			this.QuerySource = "Gallery";
			this.MappingName = "Gallery";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "LoadAllGallery]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int GalleryID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.GalleryID, GalleryID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "LoadGalleryByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter GalleryID
			{
				get
				{
					return new SqlParameter("@GalleryID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter CategoryID
			{
				get
				{
					return new SqlParameter("@CategoryID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter PhotoName
			{
				get
				{
					return new SqlParameter("@PhotoName", SqlDbType.VarChar, 50);
				}
			}
			
			public static SqlParameter OrderIndex
			{
				get
				{
					return new SqlParameter("@OrderIndex", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string GalleryID = "GalleryID";
            public const string CategoryID = "CategoryID";
            public const string PhotoName = "PhotoName";
            public const string OrderIndex = "OrderIndex";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[GalleryID] = _Gallery.PropertyNames.GalleryID;
					ht[CategoryID] = _Gallery.PropertyNames.CategoryID;
					ht[PhotoName] = _Gallery.PropertyNames.PhotoName;
					ht[OrderIndex] = _Gallery.PropertyNames.OrderIndex;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string GalleryID = "GalleryID";
            public const string CategoryID = "CategoryID";
            public const string PhotoName = "PhotoName";
            public const string OrderIndex = "OrderIndex";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[GalleryID] = _Gallery.ColumnNames.GalleryID;
					ht[CategoryID] = _Gallery.ColumnNames.CategoryID;
					ht[PhotoName] = _Gallery.ColumnNames.PhotoName;
					ht[OrderIndex] = _Gallery.ColumnNames.OrderIndex;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string GalleryID = "s_GalleryID";
            public const string CategoryID = "s_CategoryID";
            public const string PhotoName = "s_PhotoName";
            public const string OrderIndex = "s_OrderIndex";

		}
		#endregion		
		
		#region Properties
	
		public virtual int GalleryID
	    {
			get
	        {
				return base.Getint(ColumnNames.GalleryID);
			}
			set
	        {
				base.Setint(ColumnNames.GalleryID, value);
			}
		}

		public virtual int CategoryID
	    {
			get
	        {
				return base.Getint(ColumnNames.CategoryID);
			}
			set
	        {
				base.Setint(ColumnNames.CategoryID, value);
			}
		}

		public virtual string PhotoName
	    {
			get
	        {
				return base.Getstring(ColumnNames.PhotoName);
			}
			set
	        {
				base.Setstring(ColumnNames.PhotoName, value);
			}
		}

		public virtual int OrderIndex
	    {
			get
	        {
				return base.Getint(ColumnNames.OrderIndex);
			}
			set
	        {
				base.Setint(ColumnNames.OrderIndex, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_GalleryID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.GalleryID) ? string.Empty : base.GetintAsString(ColumnNames.GalleryID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.GalleryID);
				else
					this.GalleryID = base.SetintAsString(ColumnNames.GalleryID, value);
			}
		}

		public virtual string s_CategoryID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CategoryID) ? string.Empty : base.GetintAsString(ColumnNames.CategoryID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CategoryID);
				else
					this.CategoryID = base.SetintAsString(ColumnNames.CategoryID, value);
			}
		}

		public virtual string s_PhotoName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.PhotoName) ? string.Empty : base.GetstringAsString(ColumnNames.PhotoName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.PhotoName);
				else
					this.PhotoName = base.SetstringAsString(ColumnNames.PhotoName, value);
			}
		}

		public virtual string s_OrderIndex
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.OrderIndex) ? string.Empty : base.GetintAsString(ColumnNames.OrderIndex);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.OrderIndex);
				else
					this.OrderIndex = base.SetintAsString(ColumnNames.OrderIndex, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter GalleryID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.GalleryID, Parameters.GalleryID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CategoryID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CategoryID, Parameters.CategoryID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter PhotoName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.PhotoName, Parameters.PhotoName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter OrderIndex
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.OrderIndex, Parameters.OrderIndex);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter GalleryID
		    {
				get
		        {
					if(_GalleryID_W == null)
	        	    {
						_GalleryID_W = TearOff.GalleryID;
					}
					return _GalleryID_W;
				}
			}

			public WhereParameter CategoryID
		    {
				get
		        {
					if(_CategoryID_W == null)
	        	    {
						_CategoryID_W = TearOff.CategoryID;
					}
					return _CategoryID_W;
				}
			}

			public WhereParameter PhotoName
		    {
				get
		        {
					if(_PhotoName_W == null)
	        	    {
						_PhotoName_W = TearOff.PhotoName;
					}
					return _PhotoName_W;
				}
			}

			public WhereParameter OrderIndex
		    {
				get
		        {
					if(_OrderIndex_W == null)
	        	    {
						_OrderIndex_W = TearOff.OrderIndex;
					}
					return _OrderIndex_W;
				}
			}

			private WhereParameter _GalleryID_W = null;
			private WhereParameter _CategoryID_W = null;
			private WhereParameter _PhotoName_W = null;
			private WhereParameter _OrderIndex_W = null;

			public void WhereClauseReset()
			{
				_GalleryID_W = null;
				_CategoryID_W = null;
				_PhotoName_W = null;
				_OrderIndex_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter GalleryID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.GalleryID, Parameters.GalleryID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CategoryID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CategoryID, Parameters.CategoryID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter PhotoName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.PhotoName, Parameters.PhotoName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter OrderIndex
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.OrderIndex, Parameters.OrderIndex);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter GalleryID
		    {
				get
		        {
					if(_GalleryID_W == null)
	        	    {
						_GalleryID_W = TearOff.GalleryID;
					}
					return _GalleryID_W;
				}
			}

			public AggregateParameter CategoryID
		    {
				get
		        {
					if(_CategoryID_W == null)
	        	    {
						_CategoryID_W = TearOff.CategoryID;
					}
					return _CategoryID_W;
				}
			}

			public AggregateParameter PhotoName
		    {
				get
		        {
					if(_PhotoName_W == null)
	        	    {
						_PhotoName_W = TearOff.PhotoName;
					}
					return _PhotoName_W;
				}
			}

			public AggregateParameter OrderIndex
		    {
				get
		        {
					if(_OrderIndex_W == null)
	        	    {
						_OrderIndex_W = TearOff.OrderIndex;
					}
					return _OrderIndex_W;
				}
			}

			private AggregateParameter _GalleryID_W = null;
			private AggregateParameter _CategoryID_W = null;
			private AggregateParameter _PhotoName_W = null;
			private AggregateParameter _OrderIndex_W = null;

			public void AggregateClauseReset()
			{
				_GalleryID_W = null;
				_CategoryID_W = null;
				_PhotoName_W = null;
				_OrderIndex_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "InsertGallery]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.GalleryID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "UpdateGallery]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "DeleteGallery]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.GalleryID);
			p.SourceColumn = ColumnNames.GalleryID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.GalleryID);
			p.SourceColumn = ColumnNames.GalleryID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CategoryID);
			p.SourceColumn = ColumnNames.CategoryID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.PhotoName);
			p.SourceColumn = ColumnNames.PhotoName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.OrderIndex);
			p.SourceColumn = ColumnNames.OrderIndex;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
