
// Generated by MyGeneration Version # (1.2.0.2)

using VikkiSoft_BLL.DAL;

namespace VikkiSoft_BLL
{
	public class Category : _Category
	{
		public Category()
		{
		
		}

        public virtual bool LoadPrice()
        {
            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_Category_PriceLoad]");
        }

        public virtual bool LoadTitle()
        {
            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_Category_TitleLoad]");
        }
	}
}
