
// Generated by MyGeneration Version # (1.2.0.2)

using System.Collections.Specialized;
using System.Data;
using System.Data.SqlClient;
using VikkiSoft_BLL.DAL;

namespace VikkiSoft_BLL
{
	public class Merchandise : _Merchandise
	{
		public Merchandise()
		{
		
		}

        public virtual bool LoadByCategoryID(int categoryID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@CategoryID", SqlDbType.Int), categoryID);

            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_Merchandise_LoadByCategoryID]", parameters);
        }
	}
}
