
// Generated by MyGeneration Version # (1.2.0.2)

using System.Collections.Specialized;
using System.Data;
using System.Data.SqlClient;
using VikkiSoft_BLL.DAL;

namespace VikkiSoft_BLL
{
	public class OrderPhoto : _OrderPhoto
	{
		public OrderPhoto()
		{
		
		}

        public virtual bool LoadByOrderID(int orderID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@OrderID", SqlDbType.Int), orderID);

            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_OrderPhoto_LoadByOrderID]", parameters);
        }
	}
}
