
// Generated by MyGeneration Version # (1.2.0.2)

using System.Collections.Specialized;
using System.Data;
using System.Data.SqlClient;
using VikkiSoft_BLL.DAL;

namespace VikkiSoft_BLL
{
	public class PhotoSalon : _PhotoSalon
	{
		public PhotoSalon()
		{
		
		}
	}
}
