
// Generated by MyGeneration Version # (1.2.0.2)

using System.Collections.Specialized;
using System.Data;
using System.Data.SqlClient;
using VikkiSoft_BLL.DAL;

namespace VikkiSoft_BLL
{
	public class UserType : _UserType
	{
		public UserType()
		{
		
		}

        public virtual bool LoadByUserID(int userID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@UserID", SqlDbType.Int), userID);

            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_UserType_LoadByUserID]", parameters);
        }
	}
}
