
// Generated by MyGeneration Version # (1.2.0.2)

using System.Collections.Specialized;
using VikkiSoft_BLL.DAL;

namespace VikkiSoft_BLL
{
	public class UserUserType : _UserUserType
	{
		public UserUserType()
		{
		
		}

        public bool IsUserType(int userID, int userTypeID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add("@UserID", userID);
            parameters.Add("@UserTypeID", userTypeID);

            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_UserUserType_IsUserType]", parameters);
        }
	}
}
