
// Generated by MyGeneration Version # (1.2.0.2)

using VikkiSoft_BLL.DAL;

namespace VikkiSoft_BLL
{
	public class User : _User
	{
		public User()
		{
		
		}

        public bool LoadPhotographer()
        {
            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_User_LoadPhotographer]");
        }

        public virtual bool LoadWithPhotoSalonAddress()
        {
            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_User_LoadWithPhotoSalonAddress]");
        }
	}
}
